trunk/commando/board/urls.py
from django.conf.urls import patterns, include, url

from board import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<board_id>\d+)/$', views.board, name='board'),
    url(r'^move/(?P<board_id>\d+)/$', views.make_move, name='move'),
)

trunk/commando/commando/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^board/', include('board.urls', namespace="board")),
    url(r'^admin/', include(admin.site.urls)),
)

trunk/commando/board/models.py
from django.db import models
import datetime
from django.utils import timezone

def get_name_of_piece_type(piece_type):
    if piece_type == 1:
        return 'light infantry'
    if piece_type == 2:
        return 'heavy infantry'
    if piece_type == 3:
        return 'cavalry'
    raise Error('invalid piece type')

class Board(models.Model):
    #width = models.IntegerField()
    #height = models.IntegerField()
    player_to_move = models.IntegerField(default=1)
    
    def has_pieces_at(self, x, y):
        return len(self.get_pieces_at(x, y)) > 0
    def get_pieces_at(self, x, y):
        return Piece.objects.filter(board=self.pk, x=x, y=y)
    def get_pieces(self):
        return Piece.objects.filter(board=self.pk)
        
    def get_width(self):
        return 8
    def get_height(self):
        return 8
    
    def try_move(self, from_x, from_y, to_x, to_y):
        pieces = self.get_pieces_at(from_x, from_y)
        if len(pieces) == 0:
            return (False, 'No piece selected.')
        return pieces[0].try_move(to_x, to_y)

class Color:
    ORANGE = 1
    BLUE = 2
    
class PieceType:
    LIGHT_INFANTRY = 1
    HEAVY_INFANTRY = 2
    CAVALRY = 3
    
class Piece(models.Model):
    board = models.ForeignKey(Board)
    piece_type = models.IntegerField()
    x = models.IntegerField()
    y = models.IntegerField()
    owner = models.IntegerField() # 1 or 2
    
    def __unicode__(self):
        return get_name_of_piece_type(self.piece_type)
        
    def get_type_name(self):
        return get_name_of_piece_type(self.piece_type)
        
    def count_adjacent_enemies(self):
        raise NotImplementedError()
        
    def try_move(self, dest_x, dest_y):
        if self.board.player_to_move != self.owner:
            return (False, "It's not that player's turn to move.")
        if int(dest_x) == self.x and int(dest_y) == self.y:
            return (False, "Can't move in place.")
        if self.board.has_pieces_at(dest_x, dest_y):
            return (False, "Can't move onto another piece.")
        self.x = dest_x
        self.y = dest_y
        self.save()
        if self.board.player_to_move == Color.ORANGE:
            self.board.player_to_move = Color.BLUE
        else:
            self.board.player_to_move = Color.ORANGE
        self.board.save()
        return (True, None)
        

trunk/commando/board/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import messages

from board.models import Board, Piece, PieceType, Color

class IndexView(generic.ListView):
    template_name = 'board/index.html'
    context_object_name = 'board_list'

    def get_queryset(self):
        return Board.objects.all()
        
def make_move(request, board_id):
    if request.method == 'POST':
        board = get_object_or_404(Board, pk=board_id)
        from_x = request.POST['from_x']
        from_y = request.POST['from_y']
        to_x = request.POST['to_x']
        to_y = request.POST['to_y']
        
        success, fail_reason = board.try_move(from_x, from_y, to_x, to_y)
        if not success:
            messages.error(request, fail_reason)
        """#piece = board.get_pieces_at(from_x, from_y)[0]
        if piece:
            #piece.x = to_x
            #piece.y = to_y
            piece.try_move(to_x, to_y)
            piece.save()
        else:
            message = 'Invalid piece selected'"""
        #return HttpResponseRedirect(reverse('board:board', kwargs={ 'board_id': board_id, 'message':fail_reason }))
        return redirect('board:board', board_id)
        
def board(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    
    rows = []
    for y in range(0, board.get_height()):
        rows.append([])
        for x in range(0, board.get_width()):
            pieces = board.get_pieces_at(x, y)
            if len(pieces) == 0:
                rows[y].append(None)
            else:
                piece = pieces[0]
                if piece.owner == 1:
                    color = 'orange'
                elif piece.owner == 2:
                    color = 'blue'
                else:
                    raise Error('Invalid piece owner')
                    
                if board.player_to_move == Color.ORANGE:
                    to_move = 'Orange to move.'
                elif board.player_to_move == Color.BLUE:
                    to_move = 'Blue to move.'
                    
                if piece.piece_type == PieceType.LIGHT_INFANTRY:
                    rows[y].append('board/images/' + color + '-light.png')
                elif piece.piece_type == PieceType.HEAVY_INFANTRY:
                    rows[y].append('board/images/' + color + '-heavy.png')
                elif piece.piece_type == PieceType.CAVALRY:
                    rows[y].append('board/images/' + color + '-cavalry.png')
                else:
                    raise Error('Invalid piece type')
                    
    return render(request, 'board/board.html', { 'rows':rows, 'to_move':to_move, 'board':board })
    

trunk/commando/board/templates/board/board.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'board/style.css' %}" />

<center>

<table border=1>
{% for row in rows %}
	<tr>
	{% for square in row %}
		<td>
		{% with square_counter=forloop.counter0|stringformat:"s" row_counter=forloop.parentloop.counter0|stringformat:"s" %}
			{% with id=square_counter|add:","|add:row_counter %}
				
				{% if square %}
					<img src="{% static square %}" width="90" height="90" id="{{ id }}">
				{% else %}
					<div style="width:90px; height:90px;" id="{{ id }}"></div>
				{% endif %}
				
			{% endwith %}
		{% endwith %}
		</td>
	{% endfor %}
	</tr>
{% endfor %}
</table>

<p><big>{{ to_move }}</big></p>

{% if messages %}
    {% for message in messages %}
		<p>{{ message }}</p>
    {% endfor %}
{% endif %}

</center>

<form id="move" method="post" action="{% url 'board:move' board.id %}">
	{% csrf_token %}
	<input type="hidden" name="from_x" id="from_x"/>
	<input type="hidden" name="from_y" id="from_y"/>
	<input type="hidden" name="to_x" id="to_x"/>
	<input type="hidden" name="to_y" id="to_y"/>
</form>

<script>
	var selectedId = undefined

	for(var x = 0; x < 8; x += 1)
		for(var y = 0; y < 8; y += 1)
			(function(x, y) {
				var objId = x + ',' + y
				var obj = document.getElementById(objId)
				obj.addEventListener('click', function() {
					if(selectedId) {
						//document.getElementById(selectedId).className = ''
						document.getElementById('to_x').value = x
						document.getElementById('to_y').value = y
						document.forms[0].submit();
					}
					else {
						obj.className = 'selected_piece'
						selectedId = objId
						document.getElementById('from_x').value = x
						document.getElementById('from_y').value = y
					}
				})
			})(x, y)
</script>

trunk/commando/board/templates/board/index.html
{% if board_list %}
    <ul>
    {% for board in board_list %}
		<li><a href="{% url 'board:board' board.id %}">{{ board.id }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No boards are available.</p>
{% endif %}